name: flash_chat
description: A new Flutter application.

version: 1.0.0+1
environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  modal_progress_hud: ^0.1.3
  razorpay_flutter : ^1.1.1
  fluttertoast: ^3.1.0
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.0
  animations: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icon:
  android: 'launcher_icon'
  image_path: 'images/mylogo1.png'

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
